# Average home price by zip code for Lawrence KS the last 2 years

Data was provided by Zillow.com

In [43]:
import pandas as pd
import datetime
import calendar
today = datetime.datetime.now().date()
data = pd.read_csv('Zip_Zhvi_AllHomes.csv')
zips = [66044, 66046]
months = 24
data

,RegionName,City,State,Metro,CountyName,1996-04,1996-05,1996-06,1996-07,1996-08,...,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08
0,10025,New York,NY,New York,New York,NaN,NaN,NaN,NaN,NaN,...,1024600,1031500,1039700,1048400,1063000,1081200,1094200,1107800,1127600,1146200
1,60657,Chicago,IL,Chicago,Cook,142500,142100,141900,141900,142400,...,304800,305500,304800,303700,302800,302700,303100,303600,304200,304900
2,60614,Chicago,IL,Chicago,Cook,197700,194800,193300,193200,193500,...,381400,380400,379400,378400,379500,382700,386400,388500,389500,390400
3,79936,El Paso,TX,El Paso,El Paso,70800,71000,70900,71100,71000,...,112200,111900,111600,111300,111200,111300,111600,111800,112100,112100
4,10002,New York,NY,New York,New York,NaN,NaN,NaN,NaN,NaN,...,885800,901400,912100,917100,912400,910200,919600,945600,980800,1013800
5,10467,New York,NY,New York,Bronx,NaN,NaN,NaN,NaN,NaN,...,314200,317300,319100,320600,321700,321400,320900,320500,320900,321600
6,77084,Houston,TX,Houston,Harris,75200,75100,74900,74800,74700,...,132700,133400,134700,136100,137700,138900,139800,140900,142600,143800
7,94109,San Francisco,CA,San Francisco,San Francisco,277900,272000,267600,266500,265600,...,941700,949500,953900,963800,979800,1001200,1020400,1034900,1049700,1064600
8,11226,New York,NY,New York,Kings,NaN,NaN,NaN,NaN,NaN,...,631800,634500,638600,636600,631000,627700,634500,643000,646600,646700
9,60640,Chicago,IL,Chicago,Cook,100500,99500,98600,98300,98500,...,191600,191200,190600,190400,190800,191700,193400,193500,191200,188900
10,11375,New York,NY,New York,Queens,NaN,NaN,NaN,NaN,NaN,...,774900,775200,775800,776400,774600,776100,782000,788000,792600,797000
11,11235,New York,NY,New York,Kings,NaN,NaN,NaN,NaN,NaN,...,583800,587600,586900,583100,578500,575600,577200,581600,586400,590300
12,32162,The Villages,FL,The Villages,Sumter,90200,90300,89800,88700,88300,...,247600,247800,248000,248000,248000,247600,246500,245500,245100,244900
13,75070,McKinney,TX,Dallas-Fort Worth,Collin,NaN,NaN,NaN,NaN,NaN,...,232400,235600,237900,241000,244800,248500,253100,257600,261100,263100
14,90250,Hawthorne,CA,Los Angeles,Los Angeles,156200,155700,154500,153300,152500,...,468200,470900,473200,476900,480800,482600,484900,489000,494100,498200
15,37211,Nashville,TN,Nashville,Davidson,83700,84200,84700,85700,86700,...,156400,157600,158600,159600,160400,161800,163700,165800,168200,170500
16,10009,New York,NY,New York,New York,NaN,NaN,NaN,NaN,NaN,...,1070700,1100900,1123400,1130000,1126500,1129400,1136800,1153000,1176700,1198700
17,37013,Nashville,TN,Nashville,Davidson,92700,93300,94000,94700,95300,...,140100,140600,141000,141700,143000,144300,145900,147400,148700,149500
18,60647,Chicago,IL,Chicago,Cook,122300,121600,121300,121900,122500,...,275600,275900,275800,275300,275500,277300,280000,283000,286000,288300
19,77449,Cypress,TX,Houston,Harris,72300,72500,72000,71600,71300,...,135300,137000,138000,138500,139700,141600,142400,142800,144400,146300
20,10029,New York,NY,New York,New York,NaN,NaN,NaN,NaN,NaN,...,710100,709000,715000,721500,720200,720000,724500,730300,744400,761400
21,60618,Chicago,IL,Chicago,Cook,140000,139200,138400,138300,138100,...,323100,323000,321100,320500,320000,319600,321100,323800,324600,324200
22,79912,El Paso,TX,El Paso,El Paso,105400,105400,105200,104800,104400,...,164100,162800,162900,163400,163300,163500,164800,166300,166600,166500
23,90046,Los Angeles,CA,Los Angeles,Los Angeles,267400,268000,269700,273100,276700,...,1126600,1135700,1141700,1151400,1159100,1162500,1165800,1173600,1184400,1194200
24,28269,Charlotte,NC,Charlotte,Mecklenburg,106300,107000,107500,108000,108700,...,152100,152400,152800,153900,155200,156200,156900,158000,158900,159300
25,30349,Riverdale,GA,Atlanta,Clayton,90700,87900,85900,84900,83900,...,84200,85500,86100,86500,87300,87800,88200,89000,90300,91500
26,10003,New York,NY,New York,New York,NaN,NaN,NaN,NaN,NaN,...,1417100,1450700,1497300,1527700,1540700,1573900,1607500,1610500,1623600,1657400
27,94565,Pittsburg,CA,San Francisco,Contra Costa,124300,123800,123600,123700,123600,...,293000,295100,298400,302600,306600,309900,312600,314600,315900,317200
28,10462,New York,NY,New York,Bronx,NaN,NaN,NaN,NaN,NaN,...,102800,102100,102300,103300,104800,106400,108000,108800,108300,107500
29,10456,New York,NY,New York,Bronx,NaN,NaN,NaN,NaN,NaN,...,256200,258500,259900,258600,256300,255300,253000,249000,246800,246500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12908,97149,Neskowin,OR,NaN,Tillamook,NaN,NaN,NaN,NaN,NaN,...,382600,384300,387100,389400,387800,384700,386800,392000,393800,393000
12909,20625,Cobb Island,MD,Washington,Charles,130200,130700,130500,128300,124700,...,235700,233600,232600,234000,236000,236700,237800,239900,241400,241800
12910,43438,Kelleys Island,OH,Sandusky,Erie,NaN,NaN,NaN,NaN,NaN,...,231700,229200,230100,234700,240800,245800,248200,248500,245800,242500
12911,12480,Shandaken,NY,Kingston,Ulster,73200,71300,69600,68400,67800,...,155200,156300,151300,141000,132100,126300,122700,122000,124300,126600
12912,37878,Tallassee,TN,Knoxville,Blount,NaN,NaN,NaN,NaN,NaN,...,73600,74100,73200,73100,74800,76300,76600,76400,76400,76400
12913,80481,Ward,CO,Boulder,Boulder,139000,136000,134500,135300,137400,...,253000,254200,255600,257800,259500,261900,266800,273000,277900,281500
12914,97733,Crescent,OR,Klamath Falls,Klamath,91600,92400,92800,93400,95600,...,153200,151100,149700,147600,146800,147000,148000,150300,153300,154900
12915,20618,Bushwood,MD,Lexington Park,Saint Marys,117500,115500,114500,113500,113500,...,215400,215400,214100,212900,212900,212600,211200,209500,208400,207700
12916,1270,Windsor,MA,Pittsfield,Berkshire,NaN,NaN,NaN,NaN,NaN,...,198700,201500,203500,205200,206900,211300,215500,216300,216500,218800
12917,49279,Madison Township,MI,Adrian,Lenawee,NaN,NaN,NaN,NaN,NaN,...,108500,110300,111900,113000,113800,114100,114100,114800,115500,116000
12918,55703,Angora,MN,Duluth,Saint Louis,50400,50900,52100,53400,53800,...,79200,78300,78700,79000,79600,80800,82100,83800,85100,85200
12919,85931,Forest Lakes,AZ,Flagstaff,Coconino,111700,111900,112300,113500,114300,...,229900,229900,228100,225200,222500,223200,227400,230600,232100,233500
12920,6021,Colebrook,CT,Torrington,Litchfield,133800,135000,138700,142200,143000,...,238900,238700,238400,239800,241500,241400,239900,238700,238000,236900
12921,3215,Waterville Valley,NH,Lebanon,Grafton,79500,80500,81700,82600,82300,...,207300,209000,210800,214200,216000,212300,204000,197800,194800,193900
12922,98267,Marblemount,WA,Mount Vernon,Skagit,NaN,NaN,NaN,NaN,NaN,...,137400,137000,137000,139200,141500,142000,140500,139000,138700,139000
12923,3812,Hart'S Location,NH,NaN,Carroll,NaN,NaN,NaN,NaN,NaN,...,172700,170900,169700,168700,167400,167300,167900,168200,168300,168300
12924,95335,Long Barn,CA,Phoenix Lake,Tuolumne,NaN,NaN,NaN,NaN,NaN,...,202900,205600,204300,201500,200200,201600,203000,202900,204100,206300
12925,3765,Haverhill,NH,Lebanon,Grafton,70300,70100,69100,68600,68700,...,120100,120000,120000,121200,122700,123700,123700,123400,123400,123600
12926,21865,Tyaskin,MD,Salisbury,Wicomico,NaN,NaN,NaN,NaN,NaN,...,110400,109700,109400,107900,105500,103800,103300,103500,103700,104200
12927,80532,Drake,CO,Fort Collins,Larimer,131600,130900,131100,132700,134100,...,249200,248100,246400,246400,247000,248900,249400,246400,242100,239500
12928,29074,Liberty Hill,SC,Columbia,Kershaw,123800,123600,117500,110300,109900,...,209700,209700,211000,213800,215200,214900,212800,208400,204900,203600
12929,92341,Green Valley Lake,CA,Riverside,San Bernardino,NaN,NaN,NaN,NaN,NaN,...,142500,141800,142700,144500,146300,148300,150200,151100,151600,152100
12930,12429,Port Ewen,NY,Kingston,Ulster,75900,76400,77300,78600,79500,...,161800,161200,160700,160900,161500,162200,162200,161900,161200,160700
12931,84781,Pine Valley,UT,St. George,Washington,128200,128100,127900,128200,128700,...,229300,228600,227300,227000,228100,229800,228800,226200,224700,223800
12932,29915,Bluffton,SC,Hilton Head Island,Beaufort,NaN,NaN,NaN,NaN,NaN,...,504300,504900,505100,507400,513400,520900,530700,534400,523200,508100
12933,97028,Rhododendron,OR,Portland,Clackamas,161100,159100,158300,157700,156800,...,314500,316700,316200,316600,319300,322700,323800,321900,318500,315900
12934,1338,Shelburne Falls,MA,Springfield,Franklin,101400,101000,100900,100900,100500,...,204600,202900,201600,202000,203400,203700,203800,204700,205700,206200
12935,3293,Woodstock,NH,Lebanon,Grafton,75800,76300,78300,77900,74500,...,170600,171100,171400,172300,174500,176400,176100,175500,176200,176700
12936,21405,Annapolis,MD,Baltimore,Anne Arundel,258400,258400,259300,261900,264500,...,839100,842000,843400,843900,840900,832000,825700,820200,817000,817800
12937,85220,Apache Junction,AZ,Phoenix,Pinal,60900,62000,62500,62700,63500,...,168000,166100,159500,153000,149700,149100,148300,148000,147800,147600

In [46]:
for z in zips:
    print data[data.RegionName == z]

      RegionName      City State     Metro CountyName  1996-04  1996-05  \
2757       66044  Lawrence    KS  Lawrence    Douglas    79700    79000

      1996-06  1996-07  1996-08   ...     2014-11  2014-12  2015-01  2015-02  \
2757    78100    77400    77200   ...      131600   132100   132500   132400

      2015-03  2015-04  2015-05  2015-06  2015-07  2015-08
2757   131700   130900   130800   131400   131500   131200

[1 rows x 238 columns]
      RegionName      City State     Metro CountyName  1996-04  1996-05  \
4928       66046  Lawrence    KS  Lawrence    Douglas    88900    88800

      1996-06  1996-07  1996-08   ...     2014-11  2014-12  2015-01  2015-02  \
4928    88400    88300    88300   ...      139800   139900   140000   140100

      2015-03  2015-04  2015-05  2015-06  2015-07  2015-08
4928   139700   139300   139600   140200   140900   141600

[1 rows x 238 columns]

Generator that yields the string representation with the year and month of the last N months < present month

In [189]:
def last_N_months(today, N):
    if today.month > N:
        for n in range(today.month - N, today.month):
                yield datetime.date(today.year, n, today.day).strftime('%Y-%m')
    else:
        for year in range(today.year - (N / 12), today.year + 1):
            for month in range(today.month + 12 - N, today.month):
                yield datetime.date(year, month, today.day).strftime('%Y-%m')

Returns the average price of homes based on zip code and month of the year

In [190]:
def price_for_zip_by_month(zip_code, month):
    val = data[data.RegionName == zip_code][month].values
    if len(val) > 0:
        return val[0]
    else:
        return 0

In [191]:
vals = [val for val in last_N_months(today, 6)]
vals

['2015-03', '2015-04', '2015-05', '2015-06', '2015-07', '2015-08']

In [192]:
thirteen_month = ['2014-08', '2014-09', '2014-10', '2014-11', '2014-12' '2015-01', '2015-02', '2015-03', '2015-04', '2015-05', '2015-06', '2015-07', '2015-08']

In [193]:
for day in last_N_months(today, 13):
    print day

2014-08
2015-08

In [7]:
def add_months(sourcedate,months):
    month = sourcedate.month - 1 + months
    year = int(sourcedate.year + month / 12 )
    month = month % 12 + 1
    day = min(sourcedate.day,calendar.monthrange(year,month)[1])
    return datetime.date(year,month,day).strftime('%Y-%m')

In [8]:
add_months(today, -1)

'2015-08'

In [194]:
def last_N_months(today, N):
    month = today.month - 1 + N
    year = int(today.year + month / 12)
    month = month % 12 + 1
    print month
    day = min(today.day, calendar.monthrange(year, month)[1])
    start = datetime.date(today.year, month, today.day)
    for i in range(1, N + 1):
        yield datetime.date(year, month, day).strftime('&Y-%m')

In [195]:
for a in last_N_months(today, 6):
    print a

3
&Y-03
&Y-03
&Y-03
&Y-03
&Y-03
&Y-03